### PR TITLE
* **V7.8.9**

### PR DESCRIPTION
**Pull request by teknolojikpanda**
BlueStacks version 4.240.15.4204 Hyper-V support added.

### CODE REVIEW

**Comment by mathwo** [comment]
version 7.8.9 zip cannot be downloaded due to chrome and windows virus scan report.

**Comment by tm4dev** [comment]
support for BS HyperV would be great!
Thx for your work @teknolojikpanda, I got some trouble with background mode - BS HyperV 4.260.0.4207, could you give me some advice?

**Comment by woadey** [comment]
@teknolojikpanda any chance you can add support for the new 7.9.0 since the devs didn't officially release support :)

**Comment by SckyzO** [comment]
Hello dev. I think use bluestack HyperV is a very good feature. 

For example, you can't use any Android Emulator if you use WSL2 on linux. Only choice is BlueStack on HyperV. Very simple to be install, and no problem with last release. I use @teknolojikpanda branch release and work perfectly. 

What do you think about this feature @nickpavini

**Comment by SckyzO** [comment]
@teknolojikpanda Du you think you can update your version with last release ? 
Regards,

**Comment by Berkaybaba** [comment]
I am using bluestacks 5 and i am getting this error how can i fix it 
https://prnt.sc/TsRE5XqwgB5G

**Comment by Berkaybaba** [comment]
need new update

**Pull request closed without merging**
